- src/app/account/PageAccount.tsx
- src/app/account/service.ts
- src/components/FieldSelect/index.tsx
- src/components/index.ts
I made the basic front of account settings page. The feature permits to edit first name, last name, email, and language
> Account page form

- src/app/account/PageResetPasswordConfirm.tsx
- src/app/account/PageResetPasswordRequest.tsx
- src/app/account/Routes.tsx
- src/app/account/service.ts
> Reset password

- src/app/account/PagePassword.tsx
- src/app/account/service.ts
> fill password page in account

- src/app/account/PageResetPasswordConfirm.tsx
- src/app/account/PageResetPasswordRequest.tsx
- src/app/admin/users/PageUserCreate.tsx
#21 
The error was fix on PageUserCreate, PageResetPasswordConfirm and PageResetPasswordRequest. The toast will now have error's title as description
> fix errors descriptions

- src/components/ConfirmMenuItem/docs.stories.tsx
- src/components/ConfirmMenuItem/index.tsx
Co-authored-by: Ivan Dalmet <ivan@dalmet.fr>
> feat: add ConfimMenuItem

- src/app/admin/users/PageUsers.tsx
> fix: added missing / in user edition path

- src/components/Nav/index.tsx
> feat: add isMenu to the NavContext so value is shared

- src/components/FieldRadios/index.tsx
> fix: field radios showing asterisk for required status

- package.json
- src/components/FieldSelect/index.tsx
- src/components/Select/docs.stories.tsx
- src/components/Select/index.tsx
- yarn.lock
Addition of a select component using react-select and integration into FieldSelect component
> feat: add react select + integration in fieldSelect

- README.md
- package.json
- src/app/auth/AuthContext.tsx
- src/app/auth/LoginForm.tsx
- src/app/layout/Page/index.tsx
- src/app/layout/hooks/useFocusMode.ts
- src/components/DataList/docs.stories.tsx
- src/components/DayPicker/index.tsx
- src/components/FieldCurrency/docs.stories.tsx
- src/components/FieldCurrency/index.tsx
- src/components/FieldInput/docs.stories.tsx
- src/components/FieldInput/index.tsx
- src/components/InputCurrency/docs.stories.tsx
- src/components/InputCurrency/index.tsx
- src/components/TextCurrency/docs.stories.tsx
- src/components/TextCurrency/index.tsx
- src/components/index.ts
- src/test/setup.ts
- yarn.lock
- [TextCurrency preview](https://start-ui-git-format-number-bearstudio.vercel.app/storybook/index.html?path=/docs/components-textcurrency--default)
- [InputCurrency preview](https://start-ui-git-format-number-bearstudio.vercel.app/storybook/index.html?path=/docs/components-inputcurrency--default)
- [FieldCurrency preview](https://start-ui-git-format-number-bearstudio.vercel.app/storybook/index.html?path=/docs/fields-fieldcurrency--default)
> Add Currency, InputCurrency and FieldCurrency components

- package.json
- src/components/Select/index.tsx
- yarn.lock
> feat: Improve select component internal types

- README.md
Merci pour ce beau travail open-source ! Je commence seulement à l'explorer.
Concernant la PR: 
J'ai voulu corriger la faute de frappe, mais je suis rendu compte
que c'était un faux ami et qu'on avait la redondance de 'powerful'.
> docs: fix sentence

- src/locales/en/common.json
- src/locales/fr/common.json
Description: Small PR that inverts the default value of the locales which aren't well set and may confuse people.
> fix: locales test values inverted

- src/app/auth/LoginModalInterceptor.tsx
> fix: Remove trapFocus on LoginModalInterceptor fix issue with password managers

- src/components/FieldHidden/docs.stories.tsx
- src/components/FieldHidden/index.tsx
- src/components/FieldRepeater/docs.stories.tsx
- src/components/FieldRepeater/index.tsx
- src/components/index.ts
- src/locales/en/components.json
- src/locales/fr/components.json
New component `FieldRepeater` for array value.
> FieldRepeater

- package.json
- src/components/FieldCheckboxes/docs.stories.tsx
- src/components/FieldCheckboxes/index.tsx
- yarn.lock
Refactoring and adding features to the `FieldCheckboxes` component. 
- Same usage as before.
- New usage with composable components `FieldCheckboxesItem` and `FieldCheckboxesCheckAll` : 
```jsx
<FieldCheckboxes
name="colors"
label="Colors"
required="You need to check at least one color"
>
<Stack>
<FieldCheckboxesCheckAll>All colors</FieldCheckboxesCheckAll>
<Divider />
<FieldCheckboxesItem value="red">Red</FieldCheckboxesItem>
<FieldCheckboxesItem value="green">Green</FieldCheckboxesItem>
<FieldCheckboxesItem value="blue">Blue</FieldCheckboxesItem>
</Stack>
</FieldCheckboxes>
```
You can checkout the associated story file for all usages.
Value was managed using [zustand library](https://github.com/pmndrs/zustand) due to poor performances caused by re-rendering in a lot a …
> Update FieldCheckboxes component

- package.json
- src/components/FieldSelect/index.tsx
- src/components/Select/docs.stories.tsx
- src/components/Select/index.tsx
- yarn.lock
- `yarn tsc --no-emit` is OK ☑️
- `yarn lint` is OK ☑️
- `yarn test` is OK ☑️
> Update React Select to v5 (the version rewritten in TypeScript)

- src/Providers.tsx
Lazy load mirage mocks and prevent loading mock server if API url is provided
> fix: Provide async mocks and auto clean if API provided

- src/components/Select/docs.stories.tsx
- src/components/Select/index.tsx
- src/theme/foundations/index.ts
- src/theme/foundations/z-index.ts
Fix issue with select menu and portal
> fix: Select portal and z-index issue

- src/components/DayPicker/index.tsx
- src/components/FieldDayPicker/index.tsx
Fix issue with invalid date with DayPicker and FieldDayPicker
> fix: Invalid date in DayPicker

- src/components/DateSelector/DateSelector.tsx
- src/components/DateSelector/DateSelectorButton.tsx
- src/components/DateSelector/DateSelectorPicker.tsx
- src/components/DateSelector/docs.stories.tsx
- src/components/DateSelector/index.tsx
- src/components/index.ts
- src/theme/externals/reactDayPicker.ts
```jsx
<DateSelector date={selectedDate} onChange={setSelectedDate}>
<DateSelectorPreviousDayButton aria-label="Previous day" />
<DateSelectorPicker />
<DateSelectorNextDayButton aria-label="Next day" />
</DateSelector>
```
> feat: add date selector component

- src/components/FieldRadios/index.tsx
> Fix radio html name

- src/app/account/PageActivate.tsx
- src/app/account/PageResetPasswordConfirm.tsx
- src/app/account/account.service.ts
- src/app/admin/users/PageUserCreate.tsx
- src/app/admin/users/PageUserUpdate.tsx
- src/app/admin/users/users.service.ts
- src/app/layout/AccountMenu/index.tsx
- src/components/Nav/index.tsx
- src/components/Pagination/index.tsx
- src/components/SearchInput/docs.stories.tsx
- src/components/SearchInput/index.tsx
strictNullCheck set to true, going from 60+ type
issues to 33 errors and going
> feat: improve type safety

- src/components/DayPicker/index.tsx
also set monday to be the first day of the week
closes #136
> fix(#136): days were not correctly translated

- .env.example
> Added .env.example file that shows available environment variables

- src/components/FieldInput/index.tsx
- src/components/FieldTextarea/index.tsx
Add `autoFocus` on `FieldInput` and `FieldTextarea`
> feat: Add autofocus for FieldInput & FieldTextarea

- package.json
- src/types/axios.d.ts
- yarn.lock
I added the types that match our configuration. I also updated the browser list config (it automatically formatted the package.json, I did keep it).
<details>
<summary>Code</summary>
```ts
import Axios, { AxiosRequestConfig, AxiosResponse } from 'axios';
import { AUTH_TOKEN_KEY } from '@/app/auth/AuthContext';
import { isBrowser } from '@/utils/ssr';
Axios.interceptors.request.use(
(config: AxiosRequestConfig) => {
const token = isBrowser ? localStorage.getItem(AUTH_TOKEN_KEY) : null;
const authHeaders = token ? { Authorization: `Bearer ${token}` } : {};
return {
baseURL: process.env.NEXT_PUBLIC_API_BASE_URL || '/api',
...config,
headers: {
...authHeaders,
...config.headers,
},
};
},
(error) => Promise.reject(error)
);
Axios.interceptors.response.use((response: AxiosResponse) => {
if …
```
> feat: add typings for axios custom config

- src/pages/_app.tsx
Remove the `user-scalable=no` for better accessibility
Add `width=device-width`
> Update meta viewport

- src/components/Icons/IconSortAsc.tsx
- src/components/Icons/IconSortDesc.tsx
- src/components/Icons/docs.stories.tsx
- src/components/Icons/index.ts
- src/components/Sort/docs.stories.tsx
- src/components/Sort/index.tsx
- src/components/index.ts
- src/locales/ar/components.json
- src/locales/en/components.json
- src/locales/fr/components.json
Component for sort management :
- Sort by, from an array of options in props
- Sort order
> feat: Add Sort component

- public/open-api.json
- src/app/admin/users/users.service.ts
- src/mocks/openapi/paths.yaml
- src/mocks/users/index.ts
> fix: Change /users to /admin/users api for jhipster mapping

- .prettierignore
This changes is to avoid Prettier from modifying my files that are important not to be modified by a third party tool.
> feat: add .env* to prettierignore

- src/app/account/account.types.ts
- src/app/admin/users/users.types.ts
- src/app/auth/AuthContext.tsx
- src/app/layout/Page/index.tsx
- src/components/ActionsButton/index.tsx
- src/components/ConfirmMenuItem/index.tsx
- src/components/ConfirmPopover/index.tsx
- src/components/DataList/index.tsx
- src/components/DateAgo/index.tsx
- src/components/DateSelector/DateSelector.tsx
- src/components/DateSelector/DateSelectorPicker.tsx
- src/components/DayPicker/index.tsx
- src/components/FieldBooleanCheckbox/index.tsx
- src/components/FieldCheckboxes/index.tsx
- src/components/FieldCurrency/index.tsx
- src/components/FieldDayPicker/index.tsx
- src/components/FieldHidden/index.tsx
- src/components/FieldInput/index.tsx
- src/components/FieldMultiSelect/index.tsx
- src/components/FieldRadios/index.tsx
- src/components/FieldSelect/index.tsx
- src/components/FieldTextarea/index.tsx
- src/components/FormGroup/index.tsx
- src/components/Icons/Icon.tsx
- src/components/InputCurrency/index.tsx
- src/components/Nav/index.tsx
- src/components/ResponsiveIconButton/index.tsx
- src/components/SearchInput/index.tsx
- src/components/Sort/index.tsx
- src/components/TextCurrency/index.tsx
> refactor: update style code from interface to type

- package.json
- src/mocks/users/factory.ts
- yarn.lock
> Replace faker dependency

- src/components/FormGroup/index.tsx
> feat: display error message only if there is a message

- src/components/DayPicker/index.tsx
Pass the id to the DayPicker input
> fix: Pass id to the DayPicker input

- src/components/Select/index.tsx
Pass the id to the input select
> fix: Pass id to select

- src/app/account/account.service.ts
- src/app/admin/users/users.service.ts
- src/types/utilities.d.ts
Add namespace for manage query keys on service files
> add query keys registry on services

- src/app/account/account.service.ts
- src/app/admin/users/users.service.ts
Complete queryKeys "all" array for fix clear of complete cache
> Fix QueryKeys "all"

- src/components/FieldSelect/docs.stories.tsx
- src/components/FieldSelect/index.tsx
> Add isDisabled to FieldSelect FormGroup

- src/app/admin/users/PageUsers.tsx
> Fix console error in PageUsers

- src/app/layout/AccountMenu/index.tsx
Fixed the hover effect on AppVersion menu item : https://github.com/BearStudio/start-ui-web/issues/240
> fixed hover effect on AppVersion menu item

- src/components/ConfirmModal/docs.stories.tsx
- src/components/ConfirmModal/index.tsx
- src/components/ConfirmPopover/docs.stories.tsx
- src/components/ConfirmPopover/index.tsx
- src/components/index.ts
- src/locales/ar/components.json
- src/locales/en/components.json
- src/locales/fr/components.json
- src/theme/components/alert.ts
- src/theme/components/index.ts
- src/theme/components/modal.ts
- src/theme/components/popover.ts
- src/theme/foundations/colors.ts
- src/theme/styleguide/alerts.stories.mdx
- src/theme/styleguide/modals.stories.mdx
- src/theme/styleguide/popovers.stories.mdx
- [Colors Styleguide](https://start-ui-git-feat-feedback-components-bearstudio.vercel.app/storybook/index.html?path=/docs/styleguide-colors--brand)
- [Alerts Styleguide](https://start-ui-git-feat-feedback-components-bearstudio.vercel.app/storybook/index.html?path=/docs/styleguide-alerts--default-story)
- [Modals Styleguide](https://start-ui-git-feat-feedback-components-bearstudio.vercel.app/storybook/index.html?path=/docs/styleguide-modals--default-story)
- [Popovers Styleguide](https://start-ui-git-feat-feedback-components-bearstudio.vercel.app/storybook/index.html?path=/docs/styleguide-popovers--default-story)
- [ConfirmPopover isEnabled](https://start-ui-git-feat-feedback-components-bearstudio.vercel.app/storybook/index.html?path=/docs/components-confirmpopover--default#enabled-false) …
> Feedback components

- src/components/FieldBooleanCheckbox/docs.stories.tsx
- src/components/FieldBooleanCheckbox/index.tsx
- src/components/FieldCheckboxes/docs.stories.tsx
- src/components/FieldCheckboxes/index.tsx
- src/components/FieldCurrency/docs.stories.tsx
- src/components/FieldCurrency/index.tsx
- src/components/FieldDayPicker/docs.stories.tsx
- src/components/FieldDayPicker/index.tsx
- src/components/FieldHidden/docs.stories.tsx
- src/components/FieldHidden/index.tsx
- src/components/FieldInput/docs.stories.tsx
- src/components/FieldInput/index.tsx
- src/components/FieldMultiSelect/docs.stories.tsx
- src/components/FieldMultiSelect/index.tsx
- src/components/FieldRadios/docs.stories.tsx
- src/components/FieldRadios/index.tsx
- src/components/FieldSelect/docs.stories.tsx
- src/components/FieldSelect/index.tsx
- src/components/FieldTextarea/docs.stories.tsx
- src/components/FieldTextarea/index.tsx
> feat: Improve fields feedback UX

- package.json
- src/components/ConfirmMenuItem/index.tsx
- yarn.lock
Because of chakra upgrade, useStyles is depreciated and return undefined. This PR has the purpose to fix this one @charlelisefouasse contribute greatly on this fix
> Upgrade Chakra UI and update deprecated useStyles 

- package.json
- src/theme/externals-css.ts
- src/theme/externals/reactDayPicker.ts
- src/theme/foundations/typography.ts
- src/theme/index.ts
- src/theme/theme.ts
- yarn.lock
Add typing for custom theme tokens like custom colors or custom variants 🎉
https://user-images.githubusercontent.com/9749061/177938712-e37a4bf4-35e7-4187-a985-179e3a053d4d.mov
> feat: Add custom theme tokens typing

- src/components/Select/docs.stories.tsx
- src/components/Select/index.tsx
> fix: Error with loadingMessage in Select component

- .env.example
- .env.validator.js
- next.config.js
- package.json
- yarn.lock
Get instant feedback when a environment variable is missing or invalid!
> feat: Add environment variables validations

- package.json
Prettier was not triggered in pre-commit hook
> fix: Husky hooks with Prettier

- src/components/ConfirmMenuItem/index.tsx
The event was without type. 
Fixed in this pull request
> adding type on event in ConfirmMenuItem

- Dockerfile
Fix an issue with Chakra types generations
Fix #264
> fix: Docker image build

- src/components/Sort/docs.stories.tsx
- src/components/Sort/index.tsx
> fix: Sort component icon & text ellipsis issue

- README.md
Add `@latest` to the npx `create-start-ui` command to make sure that we run the latest version.
`npx create-start-ui@latest --web myApp`
> fix: Add latest to create-start-ui command

- src/app/admin/users/PageUsers.tsx
- src/app/admin/users/users.service.ts
- src/locales/ar/users.json
- src/locales/en/users.json
- src/locales/fr/users.json
Use Alert style component instead of custom render
> fix: Update style for users api error

- .env.validator.js
Typo fix is useful to CMD+Click, this PR improve Developer eXperience.
> fix: typo in console error

- package.json
> fix: package.json meta data

- package.json
- src/app/admin/users/PageUsers.tsx
- src/components/DataList/index.tsx
- yarn.lock
Implemented auto animation using react hook - useAutoAnimate() from https://auto-animate.formkit.com/#usage-react
> add AutoAnimate to DataList

- src/theme/components/badge.ts
- yarn.lock
Remove the custom style for badges for different sizes
closes #301
> fix(#301): remove the text transform rule from badge theme

- src/components/Select/index.tsx
There was an error in console cause by missing Select instanceId
> fix: Select id console error

- src/components/ConfirmModal/index.tsx
- src/components/ConfirmPopover/index.tsx
- src/components/DayPicker/index.tsx
Remove explicit any in component 
*  ConfirmPopover
*  ConfirmModal
*  Daypicker
> style(ts): replace explicit any

- README.md
- src/locales/ar/account.json
- src/locales/en/account.json
- src/locales/fr/account.json
- src/locales/sw/account.json
- src/spa/account/PageResetPasswordConfirm.tsx
> Fixed: README  ERROR

- src/spa/account/PageActivate.tsx
- src/spa/account/PagePassword.tsx
- src/spa/account/PageProfile.tsx
- src/spa/account/PageRegister.tsx
- src/spa/account/PageResetPasswordConfirm.tsx
- src/spa/account/PageResetPasswordRequest.tsx
- src/spa/admin/users/PageUserCreate.tsx
- src/spa/admin/users/PageUserUpdate.tsx
- src/spa/admin/users/PageUsers.tsx
- src/spa/auth/LoginForm.tsx
Everything is described in #341 
closes #341 
> refactor(#341): new usage of useQuery return easier to read

- src/spa/account/PageActivate.tsx
The purpose is to redirect to the login page if activate page is loaded
I added 2 toasters to alert the user of the status of the activation
closes #194
> Redirect on activate page loaded

- src/components/Page/index.tsx
- src/features/users/PageUserCreate.tsx
- src/features/users/PageUserUpdate.tsx
> fix: Back button issues

- src/app/Document.tsx
- src/app/layout.tsx
This allows to quicker plug Next Auth is need because now the root layout is a server component and not a client component anymore.
> fix: Extract client root layout into Document component

- .dockerignore
- Dockerfile
> fix: docker

- package.json
- src/app/api/jhipster-mocks/activate/route.ts
- src/features/demo-mode/DemoLoginHint.tsx
- src/features/demo-mode/DemoRegisterHint.tsx
- yarn.lock
- 🐛 Fix missing `tsx` dev dependency which causes the `yarn db:seed` to fail
- 🐛 Fix bad check on `NEXT_PUBLIC_IS_DEMO` env var, which causes the `DemoRegisterHint` to always show the demo mode alert
- 🐛 Fix bad check on `key` search param on activate user route, which causes the activation to always fail
> Fix bunch of issues

- src/components/DateSelector/docs.stories.tsx
- src/components/DayPicker/docs.stories.tsx
- src/components/FieldDayPicker/docs.stories.tsx
- src/theme/externals/reactDayPicker.ts
The day picker css overrides was not working in some conditions.
Making the css selector more specific make sure that the overrides will works better.
> fix: Day picker style

- src/theme/externals/reactDayPicker.ts
> fix: Force day picker color

- src/theme/styles.ts
Prevent visual jump between pages with and without scroll
https://github.com/BearStudio/start-ui-web/assets/9749061/403fb84d-3b38-4813-8ba4-bf301958ffa0
https://github.com/BearStudio/start-ui-web/assets/9749061/5e008152-9211-4556-af46-0e8bfb9cdaa3
> fix: Prevent visual jump between pages with and without scroll

- package.json
- src/features/auth/LoginForm.tsx
- yarn.lock
> fix: Login on safari

- src/app/app/routes.tsx
- src/components/Logo/index.tsx
- src/layout/TopBar.tsx
> Fix: multiple feedbacks

- src/locales/fr/account.json
- src/locales/fr/users.json
Fix an issue in French translation file.  
Make translations more consistent in french.
closes #373 
> fix: Improve french translation files

- src/features/auth/LoginForm.tsx
- src/features/auth/LoginModalInterceptor.tsx
> fix(#215): reset password link hack to access account reset page

- package.json
- src/components/ActionsButton/docs.stories.tsx
- src/components/ActionsButton/index.tsx
- src/components/ConfirmMenuItem/docs.stories.tsx
- src/components/ConfirmMenuItem/index.tsx
- src/components/DataList/docs.stories.tsx
- src/components/DateSelector/DateSelectorButton.tsx
- src/components/DayPicker/index.tsx
- src/components/FormGroup/index.tsx
- src/components/Icons/docs.stories.tsx
- src/components/Nav/docs.stories.tsx
- src/components/Nav/index.tsx
- src/components/Page/index.tsx
- src/components/Pagination/index.tsx
- src/components/ResponsiveIconButton/docs.stories.tsx
- src/components/SearchInput/index.tsx
- src/components/Sort/docs.stories.tsx
- src/features/account/AccountNav.tsx
- src/features/account/PageResetPasswordRequest.tsx
- src/features/admin/AdminNav.tsx
- src/features/dashboard/PageDashboard.tsx
- src/features/users/PageUsers.tsx
- src/features/users/UserActions.tsx
- src/features/users/UserStatus.tsx
- src/layout/AccountMenu.tsx
- src/layout/TopBar.tsx
- src/theme/styleguide/buttons.stories.mdx
- yarn.lock
Use lucide icons from react-icons instead of feather icons
> fix: Use lucide icons

- src/components/ActionsButton/docs.stories.tsx
- src/components/DataList/index.tsx
- src/components/DateSelector/docs.stories.tsx
- src/components/DayPicker/docs.stories.tsx
- src/components/FieldCheckboxes/index.tsx
- src/components/FieldDayPicker/docs.stories.tsx
- src/components/Page/docs.stories.tsx
- src/components/Page/index.tsx
- src/components/Select/docs.stories.tsx
- src/features/account/PagePassword.tsx
- src/features/account/PageProfile.tsx
- src/features/account/PageRegister.tsx
- src/features/account/PageResetPasswordConfirm.tsx
- src/features/account/PageResetPasswordRequest.tsx
- src/features/auth/AuthContext.tsx
- src/features/auth/LoginForm.tsx
- src/features/users/PageUserCreate.tsx
- src/features/users/PageUserUpdate.tsx
- src/theme/components/alert.ts
> Fix: Clean some todo type

- package.json
Limit node version ">=16.8.0 <19.0.0"
> fix: Node version

- README.md
- package.json
- src/features/dashboard/PageDashboard.tsx
- [do not open storybook by default](https://github.com/BearStudio/start-ui-web/commit/3494b39ca7d0871672b5e43ba2c34ea4376757fe)
- [use yarn in README for project creation](https://github.com/BearStudio/start-ui-web/commit/7a53c5caf40ea63aff0bdc0cb2c3491ca0964538)
- [github link in dashboard was the old one](https://github.com/BearStudio/start-ui-web/commit/4272df68edfbff2fc45c30e602542537a18cf120)
Not applicable
> Multiple DX improvements and fixes

- src/components/DataList/index.tsx
closes #395
- fix prop name bug
> fix: datalist prop name

- src/components/DayPicker/_partials/Day.tsx
- src/components/DayPicker/_partials/DayPickerContent.tsx
- src/components/DayPicker/matcherToArray.ts
Some code and typings improvements (comments from french to english).
> feat(daypicker): some code and typings improvements

- src/components/FieldBooleanCheckbox/index.tsx
- src/components/FieldCheckboxes/index.tsx
- src/components/FieldCurrency/docs.stories.tsx
- src/components/FieldCurrency/index.tsx
- src/components/FieldDayPicker/docs.stories.tsx
- src/components/FieldDayPicker/index.tsx
- src/components/FieldHidden/index.tsx
- src/components/FieldInput/docs.stories.tsx
- src/components/FieldInput/index.tsx
- src/components/FieldPinInput/docs.stories.tsx
- src/components/FieldPinInput/index.tsx
- src/components/FieldRadios/index.tsx
- src/components/FieldSelect/docs.stories.tsx
- src/components/FieldSelect/index.tsx
- src/components/FieldTextarea/docs.stories.tsx
- src/components/FieldTextarea/index.tsx
- src/components/FormGroup/index.tsx
- src/features/auth/LoginForm.tsx
- src/features/auth/VerificationCodeForm.tsx
- src/features/repositories/RepositoryForm.tsx
- src/features/users/UserForm.tsx
Update all fields definitions to add a more generic structure and use some Formiz V2 new stuff
> Update: new Fields definition

- src/features/account/AdminAccountNav.tsx
- src/features/admin/AdminNavBar.tsx
- src/features/admin/LinkAdmin.tsx
- src/features/app/AppNavBarDesktop.tsx
- src/features/app/AppNavBarMobile.tsx
- src/features/app/LinkApp.tsx
- src/features/auth/PageLogin.tsx
- src/features/auth/PageRegister.tsx
- src/features/management/ManagementNav.tsx
- src/features/repositories/AdminRepositoryActions.tsx
- src/features/repositories/PageAdminRepositories.tsx
- src/features/repositories/PageAdminRepository.tsx
- src/features/users/AdminUserActions.tsx
- src/features/users/PageAdminUsers.tsx
Add two new components :
* LinkApp: Link that prefix href with APP_PATH
* LinkAdmin: Link that prefix href with ADMIN_PATH
> FEAT: add LinkApp and LinkAdmin to shortcut links

- next.config.mjs
- src/features/admin-dashboard/PageAdminDashboard.tsx
- src/features/app-home/PageHome.tsx
- src/features/demo-mode/MarketingBento.tsx
Shameless plug 😅 Remember that 🚀 Start UI is free and Open Source 😉
> feat: Add marketing bento on home and dashboard

- src/lib/trpc/TrpcProvider.tsx
Only queries were allowed by Tanstack Query on dev/test without network.
Now mutation have the same behavior
Debug from React Paris 2024 😅
> fix: Allows offline mutations in dev/test mode

- src/server/config/auth.ts
- src/server/routers/auth.tsx
Add cookie expiration date and setCookie on auth check to keep user connected
> FIX: auth cookie expiration

- src/components/Select/index.tsx
Prevent issue when Select portal is enabled in a overlay element (like modal)
> fix: Select portal zindex issue

- .github/workflows/code-quality.yml
- .github/workflows/e2e-tests.yml
- Dockerfile
- README.md
- package.json
as node 18 is only in maintenance mode and node 20 is the active one, I suggest to go for 20. node 22 has been released some days ago, but it is too early to go for it at the moment in my opinion
> feat: update to node 20

- src/features/admin/AdminLayoutPage.tsx
> fix: admin layout bottom bar border

- src/features/admin/AdminCancelButton.tsx
- src/features/repositories/PageAdminRepositoryCreate.tsx
- src/features/repositories/PageAdminRepositoryUpdate.tsx
- src/features/users/PageAdminUserCreate.tsx
- src/features/users/PageAdminUserUpdate.tsx
Fixed a typo in AdminCancelButton
> fix: Typo in AdminCancelButton

- src/app/admin/(authenticated)/layout.tsx
I faced a typo error with the word "Authenticator" inside `layout.tsx` and fixed it.
- [√ ] I performed a self review of my code
- [√ ] I ensured that everything is written in English
- [√ ] I tested the feature or fix on my local environment
- [√ ] I ran the `pnpm storybook` command and everything is working
- [√ ] If applicable, I updated the translations for english and french files  
- [√ ] If applicable, I updated the README.md
- [√ ] If applicable, I created a PR or an issue on the [documentation repository](https://github.com/bearstudio/start-ui-web-docs/)
- [√ ] If applicable, I’m sure that my feature or my component is mobile first and available correctly on desktop
> fix: fix typo in layout

- .github/workflows/code-quality.yml
- .github/workflows/e2e-tests.yml
update pnpm github action version
> fix: update pnpm github action version

- src/components/Form/FieldCustom/docs.stories.tsx
Add documentation for the `custom` type on FormField to demo the usage.
> feat: Add documentation for custom field

- src/components/DayPicker/index.tsx
- src/components/Form/FieldCheckboxes/docs.stories.tsx
- src/components/Form/FieldCheckboxes/index.tsx
- src/components/Form/FieldCurrency/docs.stories.tsx
- src/components/Form/FieldCurrency/index.tsx
- src/components/Form/FieldDate/docs.stories.tsx
- src/components/Form/FieldDate/index.tsx
- src/components/Form/FieldMultiSelect/docs.stories.tsx
- src/components/Form/FieldMultiSelect/index.tsx
- src/components/Form/FieldOtp/docs.stories.tsx
- src/components/Form/FieldOtp/index.tsx
- src/components/Form/FieldPassword/docs.stories.tsx
- src/components/Form/FieldPassword/index.tsx
- src/components/Form/FieldRadios/docs.stories.tsx
- src/components/Form/FieldRadios/index.tsx
- src/components/Form/FieldSelect/docs.stories.tsx
- src/components/Form/FieldSelect/index.tsx
- src/components/Form/FieldText/docs.stories.tsx
- src/components/Form/FieldText/index.tsx
- src/components/Form/FieldTextarea/docs.stories.tsx
- src/components/Form/FieldTextarea/index.tsx
- src/components/Form/FormFieldLabel.tsx
- src/components/Select/index.tsx
- src/types/utilities.d.ts
> feat: props propagation for all fields

- src/components/FormPopover/index.tsx
- src/features/users/PageAdminUsers.tsx
- Add ref props to give the containerRef to the `FormPopover` `Portal`.
- Removed the implementation in admin interface as there are little issues with it.
> fix: formpopover container ref for improved placement

- src/emails/components/Layout.tsx
- src/emails/templates/delete-account-code.tsx
- src/emails/templates/email-address-change.tsx
- src/emails/templates/login-code.tsx
- src/emails/templates/login-not-found.tsx
- src/emails/templates/register-code.tsx
Language on html and direction (LTR / RTL) on emails
> fix: html language and direction in emails

- src/components/DayPicker/_partials/DayPickerContent.tsx
Use DayPicker zIndex from theme to prevent issue in overlays.
> fix: DayPicker zIndex issue

- src/app/Document.tsx
> fix: deprecated meta for new one

- src/components/Form/FieldSelect/docs.stories.tsx
- src/features/account/AccountEmailForm.tsx
- src/features/auth/PageRegister.tsx
Use useWatch hook from React Hook Form instead of form.watch for performance
> fix: Use useWatch hook instead of form.watch for performance

- app/lib/ui-state.ts
> V3: fix UI state typescript
