jest.config.js, src/__mocks__/styleMock.js
Fix `App.spec.test`, mock css loading from external components
=> Fix: Add mock in test for external css

src/components/Nav/index.tsx
isLazy prop could have side effect (the active state on mobile can be
out of sync) if the page is not rerendered
closes #44
=> fix: remove isLazy prop from Nav component

src/app/layout/LayoutContext/index.ts, src/app/layout/MainMenu/index.tsx, src/app/layout/NavDrawer/index.tsx, src/app/layout/TopBar/index.tsx, src/app/layout/hooks/useFocusMode.ts
By setting the `strictNullChecks` TypeScript option to `true`, I saw multiple typings problem (53 total). Here is a first change to remove 6 issues based on `LayoutContext` typings.
=> feat: improve typing for layout context

src/theme/components/index.ts, src/theme/components/popover.ts
By default in Chakra-UI, only one size is implemented for the Popover component. The [documentation](https://chakra-ui.com/docs/overlay/popover#popover-props) says that it can be implemented in the custom theme.
This MR implements all sizes available in Chakra-UI right now from "3xs" to "8xl". It also keeps the default value of Chakra-UI (xs)
=> Implement sizes for Popover component

package.json, src/components/DayPicker/index.tsx, src/theme/externals/reactDayPicker.ts, src/theme/foundations/index.ts, src/theme/foundations/z-index.ts, yarn.lock
this custom overlay use react popper to position react day picker correctly
> 💡 Also improve style.
=> fix: wrap react day picker with custom overlay

tsconfig.json
Improve type checking.
```
yarn tsc --noEmit
```
does not throw any error.
=> feat: add strict check for bind call apply

src/locales/fr/auth.json
The localization for the key `auth:interceptor.title` is not correct in french.
=> Fix: wrong localization of connection interceptor title in french

package.json
This PR aims to fix build issues on CI / Serverless environments
This is the recommended way of installing husky (https://typicode.github.io/husky/#/?id=install)
=> fix: replace postinstall npm script with prepare

.dockerignore, Dockerfile, README.md, next.config.js, package.json, yarn.lock
Update the Docker image to use the experimental `outputStandalone` feature of NextJS
```
experimental: {
outputStandalone: true,
},
```
This allow the image to go from 1Go to 129mo
Official example : https://github.com/vercel/next.js/tree/canary/examples/with-docker
=> feat: Update Docker image for lighter image (1Go to 129mo)

package.json, yarn.lock
Adding [`sharp`](https://sharp.pixelplumbing.com/) dependency for production in standalone version (like Docker).
https://nextjs.org/docs/deployment#nodejs-server
=> fix: Add missing dependency sharp for production

.npmrc, package.json
Enforce node engine 14.17+, yarn 1.22+ and types checking on lint script
Fix #152
=> Enforce node engine 14.17+, yarn 1.22+ and types checking on lint script

README.md
Adding a simple rewrite configuration for using statically built start-ui with an Apache web server.
```bash
Options -MultiViews
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule "^app/" "app.html" [QSA,L]
```
=> Add apache documentation for static build

src/components/DayPicker/index.tsx, src/types/utilities.d.ts, tsconfig.json
Example:
```ts
type CustomProps = {
placeholder?: string;
value?: string | Date | null;
onChange?: (date: Date | null | undefined, isValid: boolean) => void;
inputProps?: InputProps;
dayPickerProps?: DayPickerProps;
};
interface DayPickerProps extends Overwrite<BoxProps, CustomProps> {}
```
To avoid the `Omit` on every keys each time we add a new key in the custom props type.
```ts
interface DayPickerProps extends Omit<BoxProps, 'onChange'>  {
placeholder?: string;
value?: string | Date | null;
onChange?: (date: Date | null | undefined, isValid: boolean) => void;
inputProps?: InputProps;
dayPickerProps?: DayPickerProps;
};
```
=> feat: add generic type folder and Overwrite type

src/config/axios.ts
With this fix. We don't send Authorization token to external API. (More important if we send request on HTTP only not HTTPS public API)
It's better because we can send request to public external API and forget to remove it.
Or we can have bug because we use other authentification methods. (I had this case with Cloudinary)
=> fix: don't send API token to external API

src/components/FieldBooleanCheckbox/index.tsx
By default "isDisabled" props is not appliqued on Checkbox input
Surely because by default ChakraUI need CheckboxProvider (?)
To fix I applied mannually isDisabled props
=> fix: add manually isDisabled to Checkbox component

src/components/ConfirmPopover/docs.stories.tsx, src/components/ConfirmPopover/index.tsx, src/components/index.ts, src/locales/ar/components.json, src/locales/en/components.json, src/locales/fr/components.json
Add new ConfirmPopover component, with docs stories and translations
=> Feat: Add ConfirmPopover component

src/app/layout/Page/docs.stories.tsx, src/app/layout/Page/index.tsx
Component PageTopBar is used when there is a need to add a TopBar to a specific page in addition to the standard TopBar providede by the Layout.
Right now, the PageTopBar places itself under the Layout TopBar. When the page is scrolled, the PageTopBar is scrolled with it and goes hiding behind the LayoutTopBar.
This PR adds a new `isFixed:boolean` props to the PageTopBar. It's default value is `false` to keep the previously described behaviour. When set to `true`, the PageTopBar will stay under the Layout TopBar even when the page content is scrolled.
An exemple is added in storybook : App Layout > Page > Focus Fixed PageTopBar.
TL,DR : Added isFixed props to PageTopBar, fixes the PageTopBar right under the Layout TopBar if set to `true`. …
=> added isFixed props to PageTopBar with exemple in story

src/components/ActionsButton/ActionsButton.cy.tsx
We have a test Cypres at the file `ActionsButton.cy.tsx`, with test description `should display an accecible clickable icon`, as we see the word accessible is written wrong.
closes #232 
The file that i will edite is  `ActionsButton.cy.tsx`, is exist at `src/components/ActionsButton/ActionsButton.cy.tsx`
=> fix wording at the test of ActionsButton

src/config/dayjs.ts, src/config/i18next.ts
Before this PR, if the default language was changed, the default dayjs locale was still "en".
=> fix: Init dayjs with the current language on first load

src/components/DateAgo/index.tsx
DateAgo useEffect array dependencies was not stable across rerenders
=> fix: DateAgo array dependencies with stable reference

README.md
Add the following section in readme
When adding or updating theme components, component variations, sizes, colors and other theme foundations, you can extend the internal theme typings to provide nice autocomplete.
Just run the following commmand after updating the theme:
```bash
yarn theme:generate-typing
```
=> feat: Add Readme section for theme typing generation

src/app/account/account.service.ts, src/app/admin/users/users.service.ts
at the call api of User and Account we detect the error type with test the error key to a string, the object is change the hard code test to test it with constant instead of strings.
#79 
add constent to to User and Account at 
`src/app/admin/users/users.constants.ts` for User
and 
`src/app/account/account.constants.ts` for Account
=> Change hard coded strings to const for routing and API error keys

src/config/i18next.ts, src/constants/i18n.ts
We can remove the explicit any by writing an enum type from locale object
=> style: remove explicit any in 18n config

README.md, src/locales/ar/dashboard.json, src/locales/en/dashboard.json, src/locales/fr/dashboard.json, src/locales/sw/dashboard.json, src/spa/dashboard/PageDashboard.tsx
Add documentation links in README and on PageDashboard
Mobile : 
Desktop :
=> feat: documentation links

.gitignore, next-env.d.ts
As stated by the Next documentation:
A file named next-env.d.ts will be created at the root of your project. This file ensures Next.js types are picked up by the TypeScript compiler. You should not remove it or edit it as it can change at any time. This file should not be committed and should be ignored by version control (e.g. inside your .gitignore file).
=> feat: remove next-env.d.ts from versionning

.prettierignore
.env.validator.js was ignored by prettier
=> Allows prettier in .env.validator.js

package.json, src/spa/account/PageProfile.tsx, src/spa/account/account.service.ts, src/spa/admin/users/PageUserUpdate.tsx, src/spa/admin/users/users.service.ts, src/types/utilities.d.ts, yarn.lock
I integrate query-key-factory library to replace our custom query keys on services files.
I think it's more simple to write, to understand and to use.
=> feat: add query-key-factory library + integration

src/components/DayPicker/index.tsx
When the input is not visible, we cannot choose a date.
closes #307 
To fix this issue, we can add the keepFocus={false} attribute to the DayPickerInput component. This attribute disables the focus on the input after the user selects a date. 
https://user-images.githubusercontent.com/80390318/213213521-1b24ee2e-ff0f-4298-ac77-c5a96bbfd271.mp4
https://user-images.githubusercontent.com/80390318/213213334-73312dc6-7ccb-410a-9d94-8c68a07727ad.mp4
=> fix daypicker click when input is not visible

src/spa/router/guards/AdminRouteGuard.tsx, src/spa/router/guards/AuthenticatedRouteGuard.tsx, src/spa/router/guards/useRedirectUnauthenticated.ts
closes #340
Navigate to admin page unauthenticated does not redirect on login page like that should (and like it works on non-admin page like dashboard)
Result :
=> fix: redirect unauthenticated on admin routes

src/components/ConfirmModal/index.tsx, src/components/ConfirmPopover/index.tsx, src/components/DateSelector/DateSelector.tsx, src/components/ErrorBoundary/index.tsx, src/components/Select/docs.stories.tsx, src/spa/auth/LoginModalInterceptor.tsx, src/spa/layout/Layout/index.tsx, src/theme/styleguide/modals.stories.mdx, src/theme/styleguide/popovers.stories.mdx
Like the usage of useQuery (https://github.com/BearStudio/start-ui-web/pull/342), I think it's a better idea to not destructure ChakraUI `useDisclosure` return value, because it's more readable and that simplify disclosure definition and refactor.
For example :
Not readable or complex :
```
const { isOpen, onOpen, onClose } = useDisclosure();
const { isOpen: isOpenConfirmModal, onOpen: onOpenConfirmModal, onClose: onCloseConfirmModal } = useDisclosure();
...
<Button onClick={onOpen}>Open</Button> 
<Button onClick={onOpenConfirmModal}>Open</Button>
```
Easier and more readable :
```
const confirmModal = useDisclosure();
...
<Button onClick={confirmModal.onOpen}>Open</Button>
```
=> refactor: new usage useDisclosure return

README.md, src/app/Document.tsx, src/app/Providers.tsx, src/theme/config.ts, src/theme/index.ts
The idea is to give the user the ability to easily update the storage key used by chakra-ui to update the color mode.
This will prevent color mode conflicts when you have multiple projects using chakra-ui stack.
For implementation details, see: https://github.com/chakra-ui/chakra-ui/issues/5554#issuecomment-1128385174
Here you can see that the new key is used to detect the color mode
=> feat(theme): add custom color mode storage key

.github/workflows/code-quality.yml, package.json
change the name of the script because using nextjs linter (which may be or may not be eslint)
=> feat: change script name for lint:next because using next cli

src/components/DayPicker/docs.stories.tsx, src/components/DayPicker/hooks/useDayPickerInputManagement.ts
fix issue on the day picker. the format was changing on input blur
https://github.com/BearStudio/start-ui-web/assets/3920615/27ab7bd1-6099-44d1-a285-1825f061126a
https://github.com/BearStudio/start-ui-web/assets/3920615/3dfb85ad-48b0-4c20-9e91-530759e007d3
=> fix: daypicker format was changing on input blur

src/app/admin/layout.tsx, src/app/app/layout.tsx, src/app/layout.tsx
The first page loading in the browser was triggering a double reload (need to open a new tab to trigger, not only reload the page)
=> fix: Prevent initial page to load twice

package.json, pnpm-lock.yaml, src/components/Viewport/index.tsx, src/features/admin/AdminLayoutPage.tsx, src/features/admin/AdminNavBar.tsx, src/features/app/AppLayoutPage.tsx, src/features/docs/PageApiDocumentation.tsx, src/theme/styles.ts
Remove fixed elements in layout for easier customization without 10+ years mastering in CSS layout 😅
=> feat: simplify layout

src/components/Form/FieldCurrency/index.tsx
The start (and end) elements are overlapping on the FieldCurrency content.
This is because InputCurrency is made with a library other than ChakraUI and the stylings are not working together.
To fix that, I added a padding to the InputCurrency inside of FieldCurrency if there is an element.
I tested the field with all 4 sizes of input ('xs', 'sm', 'md', lg') and in order it gives : 
closes #474
=> Fix : FieldCurrency element overlapping on text

src/features/auth/PageLogout.tsx
closes #481 
Make the logout mutation async so that it can be awaited properly 
**Question : Is there still a point to making the optimistic update  ?**
The code before : (await has no effect)
This lead to : 
Redirection happening before the logout and triggering checkAuthenticated before the end of logout.
Reminder : `checkAuthenticated` sets a new auth cookie.
What happend before on the logout page : 
1.  Call logout
2. Redirection
3. Call checkAuthenticated (user still in context)
4. Suppression of the cookie
5. Cookie set again in checkAuthenticated
6. User not logged out
7. 
After the fix:
=> Fix(logout) : Logout not working when deployed

src/components/Form/index.tsx
Add `stopPropagation` to our custom `Form` component so nested Forms won't trigger parent forms.
Developers needs to handle the `Portal` to avoid DOM `form` in `form` themselves.
=> feat: add global stopPropagation for nested FormProviders 

src/components/Form/FormField.tsx, src/components/Form/FormFieldError.tsx, src/components/Form/FormFieldErrorStandalone/docs.stories.tsx, src/components/Form/FormFieldErrorStandalone/index.tsx
Add the `<FormFieldErrorStandalone>` component to allows rendering error anywhere not only with the field. 
Add the `displayError`  props on FormField to allows to not display the error close to the field.
=> feat: Add FormFieldErrorStandalone component

src/components/Form/FieldCheckbox/FieldCheckbox.spec.tsx, src/components/Form/FieldCheckbox/docs.stories.tsx, src/components/Form/FieldCheckbox/index.tsx, src/components/Form/FieldSwitch/FieldSwitch.spec.tsx, src/components/Form/FieldSwitch/docs.stories.tsx, src/components/Form/FieldSwitch/index.tsx, src/components/Form/FormFieldController.tsx, src/theme/components/index.ts, src/theme/components/switch.ts
- add FieldCheckbox
- add FieldSwitch
- update their theme
=> feat: add field checkbox and fieldswitch

src/lib/form/getFieldPath.ts
=> feat: add getFieldPath a function that helps with path name typings

src/components/Form/FieldCheckboxes/FieldCheckboxes.spec.tsx, src/components/Form/FieldCurrency/FieldCurrency.spec.tsx, src/components/Form/FieldDate/FieldDate.spec.tsx, src/components/Form/FieldMultiSelect/FieldMultiSelect.spec.tsx, src/components/Form/FieldOtp/FieldOtp.spec.tsx, src/components/Form/FieldPassword/FieldPassword.spec.tsx, src/components/Form/FieldPassword/index.tsx, src/components/Form/FieldRadios/FieldRadios.spec.tsx, src/components/Form/FieldSelect/FieldSelect.spec.tsx, src/components/Form/FieldText/FieldText.spec.tsx, src/components/Form/FieldTextarea/FieldTextarea.spec.tsx
closes #507 
- Do the rest of the unit tests
- Fixed a bug in FieldPassword
=> Feat : Add unit tests on FormFields if isDisabled

src/components/Form/FieldNumber/index.tsx
Add `fieldState.error` to make the input invalid when there are errors.
=> fix: handle invalid state for field number

src/components/Pagination/index.tsx
closes #279 
I put a condition on the `firstItemOnPage` props in Pagination component to display "Showing 0 to 0 of 0 results" instead of "Showing 1 to 0 of 0 results" when there is no result
Result
With these values
=> Fix : First item on pagination

src/server/config/auth.ts
Prevent to create the session if the user is not ENABLED
=> fix: don't create a session if user is not enabled

src/components/Form/FieldDate/index.tsx
=> fix: invalidate the input on form error

src/lib/form/useWatchToTrigger.ts, src/lib/form/useWatchToTrigger/docs.stories.tsx, src/lib/form/useWatchToTrigger/index.ts
add a hook to watch fields and trigger validation
=> feat: add watch to trigger hook

src/lib/form/useWatchToTrigger/docs.stories.tsx
Improve the story for the `useWatchToTrigger` hook
=> feat: improve story for the useWatchToTrigger hook

src/components/Form/FormFieldError.tsx
Prevent global form rerendering because of the form field error component
=> fix: Optimize performance of the form field error

app/components/ui/select.tsx, app/features/repository/app/page-repositories.tsx, app/features/repository/app/page-repository.tsx, app/features/repository/manager/page-repositories.tsx, app/features/repository/manager/page-repository.tsx, app/features/user/manager/page-user-update.tsx, app/features/user/manager/page-user.tsx, app/features/user/manager/page-users.tsx, app/lib/ui-state.ts
A picture is worth a thousand words.
https://github.com/user-attachments/assets/68d3421d-97be-4bc3-91bd-50c0f6f4b6df
=> FEAT: ui-state match

app/features/user/manager/page-user.tsx, app/lib/ui-state.ts
* Add `when`
* Add custom error types to improve DX
* Add possibility to autocomplete error stuff (ex: `exhaustive` even if all match are not setup), but trigger TS errors
=> V3: improve getUiState (when + error types)
